language: ruby
    
before_install:
  - gem install bundler --pre
  - gem --version

rvm:
  - 2.0.0

script: bundle exec rake

notifications:
  email:
    recipients:
      - hello@qingpei.me
    on_success: change
    on_failure: always
