language: ruby
    
before_install:
  - gem --version

rvm:
  - 2.0.0

script:
  - bundle exec rake > rake.log
  - cat rake.log
  - checkerror(){if grep -i 'error' rake.log; then return "1" else return "0" fi}
  - checkerror

notifications:
  email:
    recipients:
      - hello@qingpei.me
    on_success: change
    on_failure: always
