markdown: redcarpet
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
include: [about, blog, gallery, project]
exclude: [readme.markdown, Rakefile, r.js, optimize, scss]
